apiVersion: 1

datasources:
  - name: Tempo
    type: tempo
    uid: tempo
    access: proxy
    url: http://tempo:3200
    isDefault: true
    jsonData:
      tracesToLogsV2:
        datasourceUid: ""

  - name: ClickHouse
    type: grafana-clickhouse-datasource
    uid: clickhouse
    access: proxy
    jsonData:
      host: clickhouse
      port: 9000
      protocol: native
      username: rca
      defaultDatabase: rca_otel
      secure: false
      tlsSkipVerify: true
    secureJsonData:
      password: rca123

  - name: MySQL
    type: mysql
    uid: mysql
    access: proxy
    url: mysql:3306
    user: rca
    database: rca
    secureJsonData:
      password: rca123
    jsonData:
      maxOpenConns: 10
